apiVersion: apps/v1
kind: Deployment
metadata:
  name: estoque
  namespace: loja-veloz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: estoque
  template:
    metadata:
      labels:
        app: estoque
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: estoque
        image: rcarv/estoque:latest
        ports:
        - containerPort: 8083
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 10
          periodSeconds: 5