apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedidos
  namespace: loja-veloz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pedidos
  template:
    metadata:
      labels:
        app: pedidos
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: pedidos
        image: rcarv/pedidos:latest
        ports:
        - containerPort: 8081
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: pedidos-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: pedidos-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pedidos-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pedidos-secret
              key: DB_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5